// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: versions.sql

package sqlc

import (
	"context"
)

const insertVersion = `-- name: InsertVersion :one
INSERT INTO versions (tag) VALUES ($1) RETURNING id
`

func (q *Queries) InsertVersion(ctx context.Context, tag string) (uint64, error) {
	row := q.queryRow(ctx, q.insertVersionStmt, insertVersion, tag)
	var id uint64
	err := row.Scan(&id)
	return id, err
}
